apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-consul.fullname" . }}
  labels:
    app: {{ include "my-consul.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.p1.port }}
      targetPort: {{ .Values.service.ports.p1.port }}
      protocol: TCP
      name: p1
    - port: {{ .Values.service.ports.p2.port }}
      targetPort: {{ .Values.service.ports.p2.port }}
      protocol: UDP
      name: p2
  selector:
    app: {{ include "my-consul.name" . }}
    release: {{ .Release.Name }}