apiVersion: v1
kind: Service
metadata: 
  name: consul-server-service
  labels:
    consul: server
spec: 
  ports: 
    - 
      port: 8500
      protocol: TCP
      targetPort: 8500
      name: consul-server-ui-port
    - 
      port: 8600
      protocol: UDP
      targetPort: 8600
      name: consul-server-port
  selector: 
    consul: server
  type: NodePort