apiVersion: v1
kind: Service
metadata: 
  name: echo-service
  labels:
    app: echo
spec: 
  ports: 
    - 
      port: 5678
      protocol: TCP
      targetPort: 5678
      name: echo-port
  selector: 
    app: echo
  type: NodePort